repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.1
    hooks:
      - id: terraform_fmt
        name: Terraform -> Format
        description: Apply formating to terraform code.
      - id: terraform_tflint
        name: Terraform -> Lint
        description: Execute lint on terraform code.
        args:
          - '--args=--enable-rule=terraform_standard_module_structure'
          - '--args=--enable-rule=terraform_naming_convention'
          - '--args=--enable-rule=terraform_required_version'
          - '--args=--enable-rule=terraform_required_providers'
          - '--args=--enable-rule=terraform_documented_variables'
          - '--args=--enable-rule=terraform_documented_outputs'
          - '--args=--enable-rule=terraform_typed_variables'
          - '--args=--enable-rule=terraform_comment_syntax'
          - '--args=--disable-rule=terraform_module_pinned_source'
      - id: terraform_validate
        name: Terraform -> Validate
        description: Validate the Terraform code is syntactically valid and internally consistent.

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.18.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "."]
  
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        name: DocToc
        description: Generates table of contents for markdown files.
